services:
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: telecom-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - frontend-api-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: telecom-frontend
    restart: unless-stopped
    networks:
      - frontend-api-network

  backend:
    build:
      context: ../backend
      dockerfile: telecom.Api/Dockerfile
    container_name: telecom-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=telecom;Username=telecom_user;Password=telecom_password
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - frontend-api-network
      - db-api-network

  postgres:
    image: postgres:15
    container_name: telecom-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telecom
      POSTGRES_USER: telecom_user
      POSTGRES_PASSWORD: telecom_password
    restart: unless-stopped
    networks:
      - db-api-network

networks:
  frontend-api-network:
    name: telecom-frontend-api
    driver: bridge
  
  db-api-network:
    name: telecom-db-api
    driver: bridge
